import type { Pattern, Proposal, Category, Threshold } from '@syner/ops'
import type { Skill } from '@syner/osprotocol'

export function generateCandidate(
  pattern: Pattern,
  skill: Skill
): Proposal {
  const category = categorizeChange(pattern)
  const metrics = estimateMetrics(pattern, category)

  return {
    category,
    description: buildDescription(pattern, skill),
    diff: '', // Actual diff generated by downstream (evaluator/sandbox)
    metrics,
    skillRef: pattern.skillRef,
  }
}

function categorizeChange(pattern: Pattern): Category {
  // Trust the analyzer's suggestion, but override for high-severity structural issues
  if (pattern.severity === 'high' && pattern.suggestedCategory === 'new-skill') {
    return 'structural'
  }
  return pattern.suggestedCategory
}

function estimateMetrics(pattern: Pattern, category: Category): Threshold[] {
  const baseReduction = category === 'skill-tweak' ? 0.5 : category === 'new-skill' ? 0.7 : 0.9

  return [
    {
      metric: 'friction_frequency',
      before: pattern.frequency,
      required: Math.max(1, Math.floor(pattern.frequency * (1 - baseReduction))),
    },
    {
      metric: 'verification_pass_rate',
      before: 0, // Unknown until sandbox evaluation
      required: category === 'structural' ? 0.95 : 0.9,
    },
  ]
}

function buildDescription(pattern: Pattern, skill: Skill): string {
  const skillName = skill.name || pattern.skillRef
  return `Fix "${pattern.pattern}" in ${skillName} (observed ${pattern.frequency}x, severity: ${pattern.severity})`
}
