packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  eslint: ^9.37.0
  prettier: ^3.6.2
  typescript: ^5.9.3
  zod: ^4.1.5

catalogs:
  next15:
    next: ^15.5.4
    react: ~19.1.0
    react-dom: ~19.1.0
    '@types/node': ^20
    '@types/react': ^19
    '@types/react-dom': ^19

onlyBuiltDependencies:
  - esbuild

nodeLinker: hoisted
linkWorkspacePackages: true