packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  eslint: ^9.37.0
  prettier: ^3.6.2
  typescript: ^5.9.3
  zod: ^4.1.5
  tsup: ^8.5.0

catalogs:
  aisdk:
    ai: ^5.0.76
    zod: ^3.25.76 || ^4.1.8
  next15:
    next: ^15.5.4
    react: ^19.2.0
    react-dom: ^19.2.0
    "@types/node": ^24
    "@types/react": ^19.2.2
    "@types/react-dom": ^19.2.2

onlyBuiltDependencies:
  - esbuild

nodeLinker: hoisted
linkWorkspacePackages: true
