packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  eslint: ^9.37.0
  prettier: ^3.6.2
  typescript: ^5.9.3
  zod: ^4.1.5

onlyBuiltDependencies:
  - esbuild

nodeLinker: hoisted
linkWorkspacePackages: true