/**
 * Cron: Find Ideas
 *
 * Scheduled execution of /syner-find-ideas skill.
 * Outputs to: GitHub Issue, Vault file, Slack.
 *
 * Schedule: Mondays 9am UTC (configured in vercel.json)
 */

import { NextRequest, NextResponse } from 'next/server'
import { generateText } from 'ai'
import { anthropic } from '@ai-sdk/anthropic'
import { createThrottledOctokit, createAllTools } from '@syner/github'

const REPO_OWNER = 'synerops'
const REPO_NAME = 'syner'
const VAULT_PATH = 'apps/notes/vaults/syner/ideas'

/**
 * Load the skill instructions from the repository.
 */
async function loadSkillInstructions(
  octokit: ReturnType<typeof createThrottledOctokit>
): Promise<string> {
  const { data } = await octokit.rest.repos.getContent({
    owner: REPO_OWNER,
    repo: REPO_NAME,
    path: 'apps/md/skills/syner-find-ideas/SKILL.md',
  })

  if ('content' in data) {
    return Buffer.from(data.content, 'base64').toString('utf-8')
  }

  throw new Error('Could not load skill instructions')
}

/**
 * Load vault notes for context.
 */
async function loadVaultNotes(
  octokit: ReturnType<typeof createThrottledOctokit>
): Promise<string> {
  const notes: string[] = []

  // Get list of files in vault
  const { data: files } = await octokit.rest.repos.getContent({
    owner: REPO_OWNER,
    repo: REPO_NAME,
    path: 'apps/notes/vaults/syner',
  })

  if (!Array.isArray(files)) return ''

  // Load each markdown file (limit to avoid timeout)
  const mdFiles = files.filter((f) => f.name.endsWith('.md')).slice(0, 20)

  for (const file of mdFiles) {
    try {
      const { data } = await octokit.rest.repos.getContent({
        owner: REPO_OWNER,
        repo: REPO_NAME,
        path: file.path,
      })

      if ('content' in data) {
        const content = Buffer.from(data.content, 'base64').toString('utf-8')
        notes.push(`## ${file.name}\n\n${content}`)
      }
    } catch {
      // Skip files that can't be read
    }
  }

  return notes.join('\n\n---\n\n')
}

/**
 * Create GitHub issue with ideas.
 */
async function createGitHubIssue(
  octokit: ReturnType<typeof createThrottledOctokit>,
  ideas: string
): Promise<string> {
  const date = new Date().toISOString().split('T')[0]

  const { data } = await octokit.rest.issues.create({
    owner: REPO_OWNER,
    repo: REPO_NAME,
    title: `💡 Weekly Ideas - ${date}`,
    body: `## Generated Ideas\n\n${ideas}\n\n---\n\n*Generated automatically by syner.bot via \`/syner-find-ideas\`*`,
    labels: ['ideas', 'automated'],
  })

  return data.html_url
}

/**
 * Save ideas to vault file.
 */
async function saveToVault(
  octokit: ReturnType<typeof createThrottledOctokit>,
  ideas: string
): Promise<string> {
  const date = new Date().toISOString().split('T')[0]
  const filename = `${date}-weekly-ideas.md`
  const path = `${VAULT_PATH}/${filename}`

  const content = `---
date: ${date}
source: syner-find-ideas
type: automated
---

# Weekly Ideas - ${date}

${ideas}
`

  // Check if file exists
  let sha: string | undefined
  try {
    const { data } = await octokit.rest.repos.getContent({
      owner: REPO_OWNER,
      repo: REPO_NAME,
      path,
    })
    if ('sha' in data) {
      sha = data.sha
    }
  } catch {
    // File doesn't exist, that's fine
  }

  await octokit.rest.repos.createOrUpdateFileContents({
    owner: REPO_OWNER,
    repo: REPO_NAME,
    path,
    message: `chore: add weekly ideas ${date}`,
    content: Buffer.from(content).toString('base64'),
    sha,
  })

  return path
}

/**
 * Send to Slack (via webhook).
 */
async function sendToSlack(ideas: string): Promise<boolean> {
  const webhookUrl = process.env.SLACK_WEBHOOK_URL
  if (!webhookUrl) {
    console.log('SLACK_WEBHOOK_URL not configured, skipping Slack notification')
    return false
  }

  const date = new Date().toISOString().split('T')[0]

  const response = await fetch(webhookUrl, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      text: `💡 *Weekly Ideas - ${date}*`,
      blocks: [
        {
          type: 'header',
          text: { type: 'plain_text', text: `💡 Weekly Ideas - ${date}` },
        },
        {
          type: 'section',
          text: { type: 'mrkdwn', text: ideas.slice(0, 2900) }, // Slack limit
        },
        {
          type: 'context',
          elements: [
            {
              type: 'mrkdwn',
              text: '_Generated by syner.bot via `/syner-find-ideas`_',
            },
          ],
        },
      ],
    }),
  })

  return response.ok
}

/**
 * Verify cron secret to prevent unauthorized access.
 */
function verifyCronSecret(request: NextRequest): boolean {
  const authHeader = request.headers.get('authorization')
  const cronSecret = process.env.CRON_SECRET

  // If no secret configured, allow (for local dev)
  if (!cronSecret) return true

  return authHeader === `Bearer ${cronSecret}`
}

// Allow longer execution for AI generation
export const maxDuration = 120

export async function GET(request: NextRequest) {
  // Verify cron secret
  if (!verifyCronSecret(request)) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  try {
    const octokit = createThrottledOctokit()

    // Load skill and context
    const [skillInstructions, vaultNotes] = await Promise.all([
      loadSkillInstructions(octokit),
      loadVaultNotes(octokit),
    ])

    // Create tools for Claude
    const tools = createAllTools({ octokit })

    // Build prompt
    const systemPrompt = `You are executing the syner-find-ideas skill automatically.

${skillInstructions}

## User's Notes (Context)

${vaultNotes}
`

    // Run Claude
    const result = await generateText({
      model: anthropic('claude-sonnet-4-20250514'),
      system: systemPrompt,
      prompt:
        'Generate ideas based on the notes above. Focus on actionable startup or project ideas that leverage unique insights.',
      tools,
      maxSteps: 5,
    })

    const ideas = result.text

    // Output to all destinations in parallel
    const [issueUrl, vaultPath, slackSent] = await Promise.all([
      createGitHubIssue(octokit, ideas),
      saveToVault(octokit, ideas),
      sendToSlack(ideas),
    ])

    return NextResponse.json({
      success: true,
      outputs: {
        github: issueUrl,
        vault: vaultPath,
        slack: slackSent,
      },
    })
  } catch (error) {
    console.error('Cron find-ideas error:', error)
    return NextResponse.json(
      {
        error: 'Failed to generate ideas',
        message: error instanceof Error ? error.message : 'Unknown error',
      },
      { status: 500 }
    )
  }
}
