import { z } from "zod/v4";

export const RunSchema = z.object({
  id: z.string().describe("The unique and autogenerated identifier of the run"),

  name: z.string().describe("The name of the run"),
});
