/**
 * Orchestrator-Workers Workflow Implementation
 *
 * A central orchestrator breaks down tasks, delegates to specialized workers,
 * and synthesizes their results into a final output.
 *
 * @see https://www.anthropic.com/engineering/building-effective-agents
 */

import type { Workflow, RunOptions, Timeout, Retry, Cancel } from '../runs'
import type { Execution } from '@osprotocol/schema/runs'
import { ExecutionImpl } from '../runs/execution'

/**
 * A step in the execution plan
 */
export interface PlanStep {
  /** Unique identifier for this step */
  id: string
  /** Description of what this step accomplishes */
  description: string
  /** The worker to delegate this step to */
  worker: string
  /** Input data for this step */
  input: string
  /** IDs of steps that must complete before this step */
  dependsOn?: string[]
}

/**
 * Execution plan generated by the orchestrator
 */
export interface Plan {
  /** Ordered list of steps to execute */
  steps: PlanStep[]
  /** Overall goal of the plan */
  goal: string
}

/**
 * Result from a worker execution
 */
export interface WorkerResult<T = unknown> {
  /** ID of the step that produced this result */
  stepId: string
  /** The worker that executed the step */
  worker: string
  /** Whether execution succeeded */
  success: boolean
  /** The result data (if successful) */
  data?: T
  /** Error message (if failed) */
  error?: string
}

/**
 * Worker registration
 */
export interface WorkerConfig<T = unknown> {
  /** Unique identifier for this worker */
  name: string
  /** Description of the worker's capabilities */
  description: string
  /** The workflow this worker uses */
  workflow: Workflow<T>
  /** Types of tasks this worker can handle */
  capabilities: string[]
}

/**
 * Configuration for orchestrator-workers workflow
 */
export interface OrchestratorWorkersConfig<Output> {
  /** Function to generate execution plan */
  planner: (prompt: string) => Promise<Plan>
  /** Function to synthesize results */
  synthesizer: (results: WorkerResult[], plan: Plan) => Promise<Output>
  /** Available workers */
  workers: Record<string, WorkerConfig>
}

/**
 * Orchestrator-Workers workflow that plans, delegates, and synthesizes
 *
 * @example
 * ```typescript
 * const orchestrator = new OrchestratorWorkers({
 *   planner: async (prompt) => {
 *     // Use LLM to generate plan
 *     return { goal: prompt, steps: [...] }
 *   },
 *   synthesizer: async (results, plan) => {
 *     // Combine results into final output
 *     return combinedResult
 *   },
 *   workers: {
 *     researcher: { name: 'researcher', workflow: researchWorkflow, ... },
 *     writer: { name: 'writer', workflow: writeWorkflow, ... },
 *   }
 * })
 *
 * const execution = await orchestrator.run("Write a report on AI")
 * const result = await execution.result
 * ```
 */
export class OrchestratorWorkers<Output> implements Workflow<Output> {
  timeout?: Timeout
  retry?: Retry
  cancel?: Cancel
  onComplete?: (result: Output) => void
  onFailed?: (error: Error) => void

  constructor(public config: OrchestratorWorkersConfig<Output>) {}

  /**
   * Execute the orchestrator workflow and return an Execution handle.
   *
   * @param prompt - The input task
   * @param options - Optional run configuration
   * @returns Promise resolving to an Execution handle
   */
  async run(prompt: string, options?: RunOptions<Output>): Promise<Execution<Output>> {
    const execution = new ExecutionImpl<Output>(`orchestrator_${Date.now()}`)

    // Execute asynchronously
    this.execute(prompt, execution, options)

    return execution
  }

  /**
   * Internal execution logic
   */
  private async execute(
    prompt: string,
    execution: ExecutionImpl<Output>,
    options?: RunOptions<Output>
  ): Promise<void> {
    try {
      execution.log(`Planning: ${prompt.slice(0, 50)}...`)
      execution.updateProgress(0, 3, 'Planning')

      // 1. Generate plan
      const plan = await this.plan(prompt)
      execution.log(`Plan generated with ${plan.steps.length} steps`)
      execution.updateProgress(1, 3, 'Executing steps')

      // 2. Execute steps (respecting dependencies)
      const results = await this.executeSteps(plan, execution)
      execution.updateProgress(2, 3, 'Synthesizing results')

      // 3. Synthesize results
      const result = await this.synthesize(results, plan)

      execution.updateProgress(3, 3, 'Completed')
      execution.complete(result)

      options?.onComplete?.(result)
      this.onComplete?.(result)
    } catch (error) {
      const err = error instanceof Error ? error : new Error(String(error))
      execution.fail(err)

      options?.onFailed?.(err)
      this.onFailed?.(err)
    }
  }

  /**
   * Generate an execution plan
   *
   * @param prompt - The input task to plan
   * @returns The execution plan
   */
  async plan(prompt: string): Promise<Plan> {
    return this.config.planner(prompt)
  }

  /**
   * Delegate a step to the appropriate worker
   *
   * @param step - The plan step to execute
   * @returns The worker's result
   */
  async delegate(step: PlanStep): Promise<WorkerResult> {
    const worker = this.config.workers[step.worker]

    if (!worker) {
      return {
        stepId: step.id,
        worker: step.worker,
        success: false,
        error: `Worker "${step.worker}" not found`,
      }
    }

    try {
      const workerExecution = await worker.workflow.run(step.input)
      const data = await workerExecution.result
      return {
        stepId: step.id,
        worker: step.worker,
        success: true,
        data,
      }
    } catch (error) {
      return {
        stepId: step.id,
        worker: step.worker,
        success: false,
        error: error instanceof Error ? error.message : String(error),
      }
    }
  }

  /**
   * Synthesize worker results into final output
   *
   * @param results - Results from all workers
   * @param plan - The original plan
   * @returns The synthesized output
   */
  async synthesize(results: WorkerResult[], plan: Plan): Promise<Output> {
    return this.config.synthesizer(results, plan)
  }

  /**
   * Execute plan steps respecting dependencies
   */
  private async executeSteps(
    plan: Plan,
    execution: ExecutionImpl<Output>
  ): Promise<WorkerResult[]> {
    const results: WorkerResult[] = []
    const completed = new Set<string>()

    // Simple sequential execution for now
    // TODO(@claude): Implement parallel execution with dependency resolution
    for (const step of plan.steps) {
      // Check dependencies
      if (step.dependsOn?.some((id) => !completed.has(id))) {
        const missingDeps = step.dependsOn.filter((id) => !completed.has(id))
        results.push({
          stepId: step.id,
          worker: step.worker,
          success: false,
          error: `Missing dependencies: ${missingDeps.join(', ')}`,
        })
        continue
      }

      execution.log(`Executing step: ${step.description}`)
      const result = await this.delegate(step)
      results.push(result)

      if (result.success) {
        completed.add(step.id)
      }
    }

    return results
  }
}
