/**
 * Parallelization Workflow Implementation
 *
 * Splits a task into subtasks, executes them in parallel, and merges results.
 *
 * @see https://www.anthropic.com/engineering/building-effective-agents
 */

import type { Workflow, Run, Timeout, Retry, Cancel } from '../runs'

/**
 * A subtask generated by the split phase
 */
export interface Subtask {
  /** Unique identifier for this subtask */
  id: string
  /** The prompt/input for this subtask */
  prompt: string
  /** Optional metadata for the subtask */
  metadata?: Record<string, unknown>
}

/**
 * Result from a parallel subtask execution
 */
export interface SubtaskResult<T = unknown> {
  /** ID of the subtask */
  id: string
  /** Whether execution succeeded */
  success: boolean
  /** The result data (if successful) */
  data?: T
  /** Error message (if failed) */
  error?: string
  /** Execution time in milliseconds */
  durationMs?: number
}

/**
 * Configuration for parallelization workflow
 */
export interface ParallelizationConfig<Output, SubOutput = unknown> {
  /** Function to split input into subtasks */
  splitter: (prompt: string) => Promise<Subtask[]>
  /** Workflow to execute each subtask */
  worker: Workflow<SubOutput>
  /** Function to merge results into final output */
  merger: (results: SubtaskResult<SubOutput>[]) => Promise<Output>
  /** Maximum number of concurrent executions */
  maxConcurrency?: number
  /** Strategy for handling failures */
  failureStrategy?: 'fail-fast' | 'collect-all'
}

/**
 * Parallelization workflow that splits, executes in parallel, and merges
 *
 * @example
 * ```typescript
 * const parallel = new Parallelization({
 *   splitter: async (prompt) => {
 *     // Split into subtasks
 *     return [
 *       { id: '1', prompt: 'subtask 1' },
 *       { id: '2', prompt: 'subtask 2' },
 *     ]
 *   },
 *   worker: myWorkerWorkflow,
 *   merger: async (results) => {
 *     // Combine results
 *     return results.map(r => r.data).join('\n')
 *   },
 *   maxConcurrency: 5,
 * })
 * ```
 */
export class Parallelization<Output, SubOutput = unknown>
  implements Workflow<Output>
{
  timeout?: Timeout
  retry?: Retry
  cancel?: Cancel
  onComplete?: (result: Output) => void
  onFailed?: (error: Error) => void

  constructor(public config: ParallelizationConfig<Output, SubOutput>) {}

  /**
   * Run the parallelization workflow
   *
   * @param prompt - The input to split and process
   * @param options - Optional run configuration
   * @returns The merged output
   */
  async run(prompt: string, options?: Run<Output>): Promise<Output> {
    // 1. Split into subtasks
    const subtasks = await this.split(prompt)

    // 2. Execute in parallel
    const results = await this.parallel(subtasks, options)

    // 3. Merge results
    return this.merge(results)
  }

  /**
   * Split the input into subtasks
   *
   * @param prompt - The input to split
   * @returns Array of subtasks
   */
  async split(prompt: string): Promise<Subtask[]> {
    return this.config.splitter(prompt)
  }

  /**
   * Execute subtasks in parallel
   *
   * @param subtasks - The subtasks to execute
   * @param options - Optional run configuration
   * @returns Array of results (in same order as subtasks)
   */
  async parallel(
    subtasks: Subtask[],
    _options?: Run<Output>
  ): Promise<SubtaskResult<SubOutput>[]> {
    const maxConcurrency = this.config.maxConcurrency ?? subtasks.length
    const failFast = this.config.failureStrategy === 'fail-fast'

    const results: SubtaskResult<SubOutput>[] = []
    const queue = [...subtasks]

    // Process in batches respecting concurrency
    while (queue.length > 0) {
      const batch = queue.splice(0, maxConcurrency)

      const batchPromises = batch.map(async (subtask) => {
        const startTime = Date.now()

        try {
          // Note: options are not passed to worker - it has its own configuration
          const data = await this.config.worker.run(subtask.prompt)
          return {
            id: subtask.id,
            success: true,
            data,
            durationMs: Date.now() - startTime,
          } as SubtaskResult<SubOutput>
        } catch (error) {
          return {
            id: subtask.id,
            success: false,
            error: error instanceof Error ? error.message : String(error),
            durationMs: Date.now() - startTime,
          } as SubtaskResult<SubOutput>
        }
      })

      if (failFast) {
        // Stop on first failure
        const batchResults = await Promise.all(batchPromises)
        const failed = batchResults.find((r) => !r.success)
        if (failed) {
          throw new Error(`Subtask ${failed.id} failed: ${failed.error}`)
        }
        results.push(...batchResults)
      } else {
        // Collect all results
        const batchResults = await Promise.allSettled(batchPromises)
        for (const result of batchResults) {
          if (result.status === 'fulfilled') {
            results.push(result.value)
          } else {
            results.push({
              id: 'unknown',
              success: false,
              error: result.reason?.message ?? String(result.reason),
            })
          }
        }
      }
    }

    return results
  }

  /**
   * Merge parallel results into a single output
   *
   * @param results - Results from all parallel executions
   * @returns The merged output
   */
  async merge(results: SubtaskResult<SubOutput>[]): Promise<Output> {
    return this.config.merger(results)
  }
}
